Remove push module from AppCenter
microsoft/appcenter-sdk-apple pull request #2187
Opened 2020-10-13 10:48 UTC by AnastasiaKubova

Things to consider before you submit the PR:

* [ ] Has `CHANGELOG.md` been updated?
* [ ] Are tests passing locally?
* [x] Are the files formatted correctly?
* [ ] ~Did you add unit tests?~
* [ ] Did you check UI tests on the sample app? They are not executed on CI.
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?

## Description

- Remove Push module + targets
- Remove UI from test apps
- Remove tests
- Edit podspec
- Edit CI pipelines yaml
- Edit xcconfigs

## Related PRs or issues

AB#83306

2020-10-14 07:56 UTC, MatkovIvan requested changes

2020-10-14 07:56 UTC, MatkovIvan commented on CHANGELOG.md
> +App Center Push is [retired](https://aka.ms/MBaaS-retirement-blog-post) and has been removed from the SDK.
Be more detailed, mentioned about replacement, end of operation date.  Link does not work

2020-10-15 06:50 UTC, vvechkanov submitted a review, later dismissed

2020-10-16 06:27 UTC, vvechkanov approved these changes

2020-10-16 08:03 UTC, MatkovIvan approved these changes

2020-10-16 10:11 UTC, russelarms approved these changes

2020-10-16 10:33 UTC, merged