Fix imports for SwiftPM
microsoft/appcenter-sdk-apple pull request #2231
Opened 2020-11-25 10:57 UTC by AnastasiaKubova

Things to consider before you submit the PR:

* [ ] ~Has `CHANGELOG.md` been updated?~
* [x] Are tests passing locally?
* [x] Are the files formatted correctly?
* [ ] ~Did you add unit tests?~
* [x] Did you check UI tests on the sample app? They are not executed on CI.
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?

## Description

Reproducing steps
- Add SwiftPM from the develop branch to app
- Build app
- See error `"SomeHeader.h" file not found`.

## Related PRs or issues

AB#83931

2020-11-27 14:39 UTC, russelarms submitted a review, later dismissed

2020-11-30 11:40 UTC, DmitriyKirakosyan submitted a review, later dismissed

2020-11-30 18:30 UTC, MatkovIvan requested changes

2020-11-30 18:30 UTC, MatkovIvan commented on AppCenter/AppCenter/AppCenter.h
> +    && __has_include(<AppCenter/MSACWrapperSdk.h>)
Wow. It's not actually required, it can be just like:
```suggestion
#if __has_include(<AppCenter/MSACAppCenter.h>)
```

2020-12-02 14:32 UTC, MatkovIvan commented on AppCenterAnalytics/AppCenterAnalytics/MSACAnalytics.h
> +&& __has_include(<AppCenterAnalytics/MSACAnalyticsTransmissionTarget.h>)
Same

2020-12-02 14:32 UTC, MatkovIvan commented on AppCenterAnalytics/AppCenterAnalytics/TransmissionTarget/MSACAnalyticsTransmissionTarget.h
> +    && __has_include(<AppCenterAnalytics/MSACPropertyConfigurator.h>)
Same

2020-12-02 14:32 UTC, MatkovIvan commented on AppCenterCrashes/AppCenterCrashes/MSACCrashes.h
> +    && __has_include(<AppCenterCrashes/MSACErrorReport.h>)
Same

2020-12-02 14:32 UTC, MatkovIvan commented on AppCenterDistribute/AppCenterDistribute/MSACDistribute.h
> +    && __has_include(<AppCenterDistribute/MSACDistributeDelegate.h>)
Same

2020-12-03 06:33 UTC, AnastasiaKubova commented on AppCenterAnalytics/AppCenterAnalytics/MSACAnalytics.h
> +&& __has_include(<AppCenterAnalytics/MSACAnalyticsTransmissionTarget.h>)
These imports from different modules.

2020-12-03 06:33 UTC, AnastasiaKubova commented on AppCenterCrashes/AppCenterCrashes/MSACCrashes.h
> +    && __has_include(<AppCenterCrashes/MSACErrorReport.h>)
These imports from different modules.

2020-12-03 06:33 UTC, AnastasiaKubova commented on AppCenterDistribute/AppCenterDistribute/MSACDistribute.h
> +    && __has_include(<AppCenterDistribute/MSACDistributeDelegate.h>)
These imports from different modules.

2020-12-03 10:05 UTC, MatkovIvan approved these changes

2020-12-03 10:13 UTC, MatkovIvan requested changes
Add `_H` suffix for guards

2020-12-03 10:13 UTC, MatkovIvan commented on AppCenterAnalytics/AppCenterAnalytics/Model/MSACEventLog.h
> +#ifndef MSAC_EVENT_LOG
```suggestion
#ifndef MSAC_EVENT_LOG_H
```

2020-12-03 10:51 UTC, MatkovIvan approved these changes

2020-12-03 10:51 UTC, merged