Fix setting nil value for attachments
microsoft/appcenter-sdk-apple pull request #2235
Opened 2020-11-30 08:22 UTC by AnastasiaKubova

Things to consider before you submit the PR:

* [x] Has `CHANGELOG.md` been updated?
* [x] Are tests passing locally?
* [x] Are the files formatted correctly?
* [ ] ~Did you add unit tests?~
* [x] Did you check UI tests on the sample app? They are not executed on CI.
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?

## Related PRs or issues

AB#83924

2020-11-30 18:25 UTC, MatkovIvan requested changes

2020-11-30 18:25 UTC, MatkovIvan commented on AppCenterCrashes/AppCenterCrashes/MSACCrashesDelegate.h
> -NS_ASSUME_NONNULL_BEGIN
Almost every parameter in this class must be non null. Incorrect fix.

2020-12-02 14:31 UTC, MatkovIvan requested changes

2020-12-02 14:31 UTC, MatkovIvan commented on CHANGELOG.md
> +* **[Fix]** Fix setting `nil` for attachments in the error report.
This description is not clear. Add details that it's a listener and that signature of one method is changed.

2020-12-03 10:10 UTC, MatkovIvan commented on CHANGELOG.md
> +* **[Fix]** Change the API for the `attachmentsWithCrashes` delegate for the opportunity to set attachments value to `nil` before sending.
```suggestion
* **[Fix]** Fix nullability for attachments methods in crashes delegate. `nil` is valid return value now (4.0.0 regression).
```

2020-12-03 10:51 UTC, MatkovIvan approved these changes

2020-12-03 11:37 UTC, Jamminroot approved these changes

2020-12-03 13:53 UTC, merged